# This is a basic workflow to help you get started with Actions

name: Docker Image CI

# Controls when the workflow will run
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the tagged Docker image
          working-directory: strapi-v4
          run: docker build . --file Dockerfile --tag strapi/v4:${{steps.vars.outputs.tag}}
        - name: Push the tagged Docker image
          working-directory: strapi-v4
          run: docker push strapi/v4:${{steps.vars.outputs.tag}}
        - name: Build the latest Docker image
          working-directory: strapi-v4
          run: docker build . --file Dockerfile --tag strapi/v4:latest
        - name: Push the latest Docker image
          working-directory: strapi-v4
          run: docker push strapi/v4:latest
      
